// Barrel de los detectores. SÓLO re-exporta: el mapa que los registra vive en
// `detectores.ts`, que es quien lo consume (ver rules/codigo.md · "Un `index` de carpeta
// que agrupa sólo re-exporta").
export { archivoExtenso } from "./archivo-extenso.ts"
export { archivoIndivisible } from "./archivo-indivisible.ts"
export { centinelaSinFiltro } from "./centinela-sin-filtro.ts"
export { checkInlineEnum } from "./check-inline-enum.ts"
export { componenteFueraDeCarpeta } from "./componente-fuera-de-carpeta.ts"
export { demasiadosUseState } from "./demasiados-use-state.ts"
export { dosComponentesEnArchivo } from "./dos-componentes-en-archivo.ts"
export { estadoAccedidoPorCamino } from "./estado-accedido-por-camino.ts"
export { gateIncompleto } from "./gate-incompleto.ts"
export { indexQueDefine } from "./index-que-define.ts"
export { jsxEnProp } from "./jsx-en-prop.ts"
export { marcaMalFormada } from "./marca-mal-formada.ts"
export { marcaSinInventario } from "./marca-sin-inventario.ts"
export { markupSustancial } from "./markup-sustancial.ts"
export { objetoLiteralEnReturn } from "./objeto-literal-en-return.ts"
export { reglaSinCheck } from "./regla-sin-check.ts"
export { styleInline } from "./style-inline.ts"
export { tablaEnComponente } from "./tabla-en-componente.ts"
export { textoSinTraducir } from "./texto-sin-traducir.ts"
export { tresTiposOMas } from "./tres-tipos-o-mas.ts"
export { LIMITE_BLANDO, LIMITE_DURO } from "./limites.ts"
