import type { Paciente, Cita, HipaaLog, HipaaIncidente, HipaaTraining } from './types'
import { formatDate, addDays } from './dates'

// Datos demo del módulo medical (sin backend — fuente de verdad in-memory).
export function generateDemoData() {
  const pacientes: Paciente[] = [
    { id: 'p1', mrn: 'MRN-2024-0001', nombre: 'Maria', apellido: 'Rodriguez', fecha_nacimiento: '1985-03-15', genero: 'Femenino', telefono: '(305) 555-0101', email: 'maria.r@email.com', seguro: 'Blue Cross', seguro_id: 'BC-8834521', direccion: '1234 NW 7th St, Miami, FL 33125', estado: 'activo', alergias: 'Penicilina', condiciones: 'Hipertension, Diabetes Tipo 2', notas: '', created_at: '2024-01-10', updated_at: '2024-03-20' },
    { id: 'p2', mrn: 'MRN-2024-0002', nombre: 'Carlos', apellido: 'Mendez', fecha_nacimiento: '1972-08-22', genero: 'Masculino', telefono: '(305) 555-0102', email: 'carlos.m@email.com', seguro: 'Medicare', seguro_id: 'MC-7721934', direccion: '567 SW 8th Ave, Miami, FL 33130', estado: 'activo', alergias: 'Ninguna', condiciones: 'Artritis reumatoide', notas: 'Paciente de investigacion ERG-042', created_at: '2024-01-15', updated_at: '2024-04-01' },
    { id: 'p3', mrn: 'MRN-2024-0003', nombre: 'Ana', apellido: 'Torres', fecha_nacimiento: '1990-11-03', genero: 'Femenino', telefono: '(786) 555-0201', email: 'ana.t@email.com', seguro: 'Aetna', seguro_id: 'AE-5543219', direccion: '890 Brickell Ave, Miami, FL 33131', estado: 'activo', alergias: 'Sulfonamidas, Latex', condiciones: 'Asma', notas: '', created_at: '2024-02-01', updated_at: '2024-03-15' },
    { id: 'p4', mrn: 'MRN-2024-0004', nombre: 'Roberto', apellido: 'Vargas', fecha_nacimiento: '1965-05-28', genero: 'Masculino', telefono: '(305) 555-0303', email: 'roberto.v@email.com', seguro: 'UnitedHealth', seguro_id: 'UH-3321876', direccion: '2345 Collins Ave, Miami Beach, FL 33140', estado: 'activo', alergias: 'Aspirina', condiciones: 'EPOC, Hipertension', notas: 'Requiere interprete', created_at: '2024-02-10', updated_at: '2024-04-05' },
    { id: 'p5', mrn: 'MRN-2024-0005', nombre: 'Isabella', apellido: 'Fernandez', fecha_nacimiento: '1998-01-14', genero: 'Femenino', telefono: '(786) 555-0404', email: 'isabella.f@email.com', seguro: 'Cigna', seguro_id: 'CG-9912345', direccion: '678 Coral Way, Miami, FL 33145', estado: 'activo', alergias: 'Ninguna', condiciones: 'Ninguna', notas: 'Paciente nueva — primer consulta', created_at: '2024-03-01', updated_at: '2024-03-01' },
    { id: 'p6', mrn: 'MRN-2024-0006', nombre: 'Pedro', apellido: 'Gutierrez', fecha_nacimiento: '1955-12-08', genero: 'Masculino', telefono: '(305) 555-0505', email: 'pedro.g@email.com', seguro: 'Medicare', seguro_id: 'MC-1187654', direccion: '1111 SW 1st St, Miami, FL 33130', estado: 'alta', alergias: 'Codeine', condiciones: 'Insuficiencia cardiaca, Fibrilacion auricular', notas: 'Alta medica 2024-03-15', created_at: '2023-11-20', updated_at: '2024-03-15' },
    { id: 'p7', mrn: 'MRN-2024-0007', nombre: 'Lucia', apellido: 'Morales', fecha_nacimiento: '1988-07-19', genero: 'Femenino', telefono: '(786) 555-0606', email: 'lucia.m@email.com', seguro: 'Humana', seguro_id: 'HU-4456789', direccion: '3456 NE 2nd Ave, Miami, FL 33137', estado: 'activo', alergias: 'Ibuprofeno', condiciones: 'Migranas cronicas', notas: '', created_at: '2024-01-25', updated_at: '2024-04-08' },
    { id: 'p8', mrn: 'MRN-2024-0008', nombre: 'Fernando', apellido: 'Castillo', fecha_nacimiento: '1978-04-02', genero: 'Masculino', telefono: '(305) 555-0707', email: 'fernando.c@email.com', seguro: 'Privado', seguro_id: 'PV-0098765', direccion: '5678 SW 72nd St, Miami, FL 33143', estado: 'activo', alergias: 'Ninguna', condiciones: 'Hipotiroidismo', notas: 'Paciente de investigacion ERG-038', created_at: '2024-02-20', updated_at: '2024-04-02' },
  ]

  const hoy = new Date()
  const citas: Cita[] = [
    { id: 'c1', paciente_id: 'p1', paciente_nombre: 'Maria Rodriguez', tipo: 'Seguimiento', fecha: formatDate(hoy), hora: '09:00', duracion: 30, doctor: 'Dr. Javier Andrade', estado: 'confirmada', notas: 'Control de presion', sala: 'Consultorio A', created_at: '2024-04-01' },
    { id: 'c2', paciente_id: 'p2', paciente_nombre: 'Carlos Mendez', tipo: 'Consulta General', fecha: formatDate(hoy), hora: '09:30', duracion: 45, doctor: 'Dra. Dayrelis Mesa-Sardina', estado: 'programada', notas: 'Revision de artritis', sala: 'Sala 1', created_at: '2024-04-02' },
    { id: 'c3', paciente_id: 'p3', paciente_nombre: 'Ana Torres', tipo: 'Laboratorio', fecha: formatDate(hoy), hora: '10:00', duracion: 15, doctor: 'Dr. Leonardo Salazar', estado: 'en_curso', notas: 'Panel metabolico completo', sala: 'Sala 2', created_at: '2024-04-03' },
    { id: 'c4', paciente_id: 'p7', paciente_nombre: 'Lucia Morales', tipo: 'Especialidad', fecha: formatDate(hoy), hora: '10:30', duracion: 60, doctor: 'Dra. Diana Hernandez', estado: 'programada', notas: 'Evaluacion neurologia', sala: 'Consultorio B', created_at: '2024-04-04' },
    { id: 'c5', paciente_id: 'p4', paciente_nombre: 'Roberto Vargas', tipo: 'Telemedicina', fecha: formatDate(hoy), hora: '11:00', duracion: 30, doctor: 'Dr. Javier Andrade', estado: 'programada', notas: 'Seguimiento EPOC', sala: 'Telemedicina', created_at: '2024-04-04' },
    { id: 'c6', paciente_id: 'p5', paciente_nombre: 'Isabella Fernandez', tipo: 'Consulta General', fecha: formatDate(addDays(hoy, 1)), hora: '09:00', duracion: 45, doctor: 'Dra. Dayrelis Mesa-Sardina', estado: 'programada', notas: 'Primera consulta', sala: 'Consultorio A', created_at: '2024-04-05' },
    { id: 'c7', paciente_id: 'p8', paciente_nombre: 'Fernando Castillo', tipo: 'Seguimiento', fecha: formatDate(addDays(hoy, 1)), hora: '10:00', duracion: 30, doctor: 'Dr. Leonardo Salazar', estado: 'programada', notas: 'Control tiroides', sala: 'Sala 1', created_at: '2024-04-05' },
    { id: 'c8', paciente_id: 'p1', paciente_nombre: 'Maria Rodriguez', tipo: 'Laboratorio', fecha: formatDate(addDays(hoy, 2)), hora: '08:30', duracion: 15, doctor: 'Dr. Javier Andrade', estado: 'programada', notas: 'HbA1c', sala: 'Sala 2', created_at: '2024-04-05' },
    { id: 'c9', paciente_id: 'p2', paciente_nombre: 'Carlos Mendez', tipo: 'Procedimiento', fecha: formatDate(addDays(hoy, -1)), hora: '14:00', duracion: 60, doctor: 'Dra. Diana Hernandez', estado: 'completada', notas: 'Infiltracion articular', sala: 'Sala 3', created_at: '2024-04-01' },
    { id: 'c10', paciente_id: 'p4', paciente_nombre: 'Roberto Vargas', tipo: 'Consulta General', fecha: formatDate(addDays(hoy, -2)), hora: '11:00', duracion: 30, doctor: 'Dr. Javier Andrade', estado: 'no_show', notas: '', sala: 'Consultorio A', created_at: '2024-03-30' },
  ]

  const auditLogs: HipaaLog[] = [
    { id: 'l1', usuario_email: 'daniel@eminat.net', usuario_nombre: 'Daniel Valderrama', accion: 'VIEW_PHI', recurso: 'medical_records', paciente_id: 'p1', paciente_nombre: 'Maria Rodriguez', detalles: 'Acceso a historial medico completo', ip: '192.168.1.45', timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(), nivel: 'info' },
    { id: 'l2', usuario_email: 'dmsardina@eminat.net', usuario_nombre: 'Dayrelis Mesa-Sardina', accion: 'EDIT_PHI', recurso: 'patient_demographics', paciente_id: 'p2', paciente_nombre: 'Carlos Mendez', detalles: 'Actualizacion de informacion de seguro', ip: '192.168.1.32', timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(), nivel: 'info' },
    { id: 'l3', usuario_email: 'daniel@eminat.net', usuario_nombre: 'Daniel Valderrama', accion: 'EXPORT_PHI', recurso: 'lab_results', paciente_id: 'p3', paciente_nombre: 'Ana Torres', detalles: 'Exportacion de resultados de laboratorio para referencia', ip: '192.168.1.45', timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(), nivel: 'warning' },
    { id: 'l4', usuario_email: 'freddy@eminat.net', usuario_nombre: 'Freddy Crespin', accion: 'VIEW_PHI', recurso: 'appointment_schedule', paciente_id: '', paciente_nombre: '', detalles: 'Acceso al calendario de citas — modulo Medical', ip: '192.168.1.88', timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(), nivel: 'info' },
    { id: 'l5', usuario_email: 'daniel@eminat.net', usuario_nombre: 'Daniel Valderrama', accion: 'CREATE_RECORD', recurso: 'patient_registration', paciente_id: 'p8', paciente_nombre: 'Fernando Castillo', detalles: 'Registro de nuevo paciente', ip: '192.168.1.45', timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(), nivel: 'info' },
    { id: 'l6', usuario_email: 'dmsardina@eminat.net', usuario_nombre: 'Dayrelis Mesa-Sardina', accion: 'PRINT_PHI', recurso: 'prescription', paciente_id: 'p4', paciente_nombre: 'Roberto Vargas', detalles: 'Impresion de receta medica', ip: '192.168.1.32', timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(), nivel: 'warning' },
    { id: 'l7', usuario_email: 'lsalazar@eminat.net', usuario_nombre: 'Leonardo Salazar', accion: 'VIEW_PHI', recurso: 'medical_records', paciente_id: 'p7', paciente_nombre: 'Lucia Morales', detalles: 'Revision de historial para cita', ip: '192.168.1.55', timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(), nivel: 'info' },
    { id: 'l8', usuario_email: 'diana@eminat.net', usuario_nombre: 'Diana Hernandez', accion: 'FAILED_ACCESS', recurso: 'medical_records', paciente_id: 'p6', paciente_nombre: 'Pedro Gutierrez', detalles: 'Intento de acceso sin autorizacion — paciente dado de alta', ip: '192.168.1.60', timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(), nivel: 'critical' },
  ]

  const incidentes: HipaaIncidente[] = [
    { id: 'i1', titulo: 'PHI expuesto en impresora compartida', descripcion: 'Documentos con informacion de paciente dejados en impresora del area comun durante 15 minutos.', tipo: 'near_miss', severidad: 'media', estado: 'resuelto', reportado_por: 'Daniel Valderrama', fecha_incidente: '2024-03-28', fecha_resolucion: '2024-03-28', acciones_correctivas: 'Protocolo de impresion segura implementado. Impresora reasignada a area restringida.', created_at: '2024-03-28' },
    { id: 'i2', titulo: 'Email con PHI enviado sin cifrar', descripcion: 'Resultados de laboratorio enviados a paciente via email regular sin cifrado.', tipo: 'violation', severidad: 'alta', estado: 'investigando', reportado_por: 'Dayrelis Mesa-Sardina', fecha_incidente: '2024-04-02', fecha_resolucion: null, acciones_correctivas: 'En proceso — evaluando implementacion de portal seguro de pacientes.', created_at: '2024-04-02' },
    { id: 'i3', titulo: 'Acceso no autorizado a expediente', descripcion: 'Empleado accedio a expediente de familiar sin justificacion clinica.', tipo: 'breach', severidad: 'alta', estado: 'abierto', reportado_por: 'Daniel Valderrama', fecha_incidente: '2024-04-07', fecha_resolucion: null, acciones_correctivas: '', created_at: '2024-04-07' },
  ]

  const trainings: HipaaTraining[] = [
    { id: 't1', usuario_email: 'daniel@eminat.net', usuario_nombre: 'Daniel Valderrama', curso: 'HIPAA Privacy Rule Fundamentals', fecha_completado: '2024-01-15', fecha_vencimiento: '2025-01-15', estado: 'completado', puntuacion: 96 },
    { id: 't2', usuario_email: 'dmsardina@eminat.net', usuario_nombre: 'Dayrelis Mesa-Sardina', curso: 'HIPAA Privacy Rule Fundamentals', fecha_completado: '2024-01-18', fecha_vencimiento: '2025-01-18', estado: 'completado', puntuacion: 100 },
    { id: 't3', usuario_email: 'lsalazar@eminat.net', usuario_nombre: 'Leonardo Salazar', curso: 'HIPAA Privacy Rule Fundamentals', fecha_completado: '2024-02-01', fecha_vencimiento: '2025-02-01', estado: 'completado', puntuacion: 92 },
    { id: 't4', usuario_email: 'diana@eminat.net', usuario_nombre: 'Diana Hernandez', curso: 'HIPAA Privacy Rule Fundamentals', fecha_completado: '2024-02-05', fecha_vencimiento: '2025-02-05', estado: 'completado', puntuacion: 88 },
    { id: 't5', usuario_email: 'daniel@eminat.net', usuario_nombre: 'Daniel Valderrama', curso: 'HIPAA Security Rule & Cybersecurity', fecha_completado: '2024-03-10', fecha_vencimiento: '2025-03-10', estado: 'completado', puntuacion: 94 },
    { id: 't6', usuario_email: 'dmsardina@eminat.net', usuario_nombre: 'Dayrelis Mesa-Sardina', curso: 'HIPAA Security Rule & Cybersecurity', fecha_completado: null, fecha_vencimiento: '2024-04-30', estado: 'pendiente', puntuacion: null },
    { id: 't7', usuario_email: 'lsalazar@eminat.net', usuario_nombre: 'Leonardo Salazar', curso: 'HIPAA Security Rule & Cybersecurity', fecha_completado: null, fecha_vencimiento: '2024-03-15', estado: 'vencido', puntuacion: null },
    { id: 't8', usuario_email: 'diana@eminat.net', usuario_nombre: 'Diana Hernandez', curso: 'Breach Notification Procedures', fecha_completado: null, fecha_vencimiento: '2024-05-15', estado: 'pendiente', puntuacion: null },
    { id: 't9', usuario_email: 'freddy@eminat.net', usuario_nombre: 'Freddy Crespin', curso: 'HIPAA for Marketing Teams', fecha_completado: '2024-02-20', fecha_vencimiento: '2025-02-20', estado: 'completado', puntuacion: 90 },
  ]

  return { pacientes, citas, auditLogs, incidentes, trainings }
}
